### ISSUE TITLE
Move XSD from "docs" folder to "resources" one

### ISSUE THREAD

**Issue by depryf** [depryf/naaccr-xml#18]
Docs isn't released with the Jar file. I need to move it to resources.

I also need to put in place some tests that will make sure the java implementation (which doesn't use the XSD for syntax validation) agrees with the XSD definition.

**Comment by depryf** [comment]
The current dictionary XSD has a missing tag (so it's invalid right now); I will fix it.

Also, it has a "any attributes" on the root level; I know we have added that feature for the data, but I don't think we want that for the dictionary. At least not now. So I will remove it for now; we can easily re-add it later if some people think it's useful.

Once I am done moving the files, I would like to delete the ones from the docs folder to avoid any confusion.

**Comment by r-friedman** [comment]
I think we should keep the anyAttributes and anys at all levels.  They're key to backward compatibility (attributes added in a later version will be accepted by the anyAttribute in the earlier version).  It doesn't hurt to have them, they won't be accessible until we have an API or others write their own reader.

**Comment by depryf** [comment]
OK, I will keep them, but the library won't follow that behavior (it will fail if another attribute is added). This probably doesn't matter; this is for the dictionary only, and very few people will create their dictionary by hand once we have a GUI to create them.

**Comment by r-friedman** [comment]
Does the conversion fail if there are non-standard attributes orelements at other levels? I think unknown attributes or elements should just be ignored if possible. The API will handle the full xsd when we build it.




Sent from my Samsung Epic™ 4G TouchFabian Depry <notifications@github.com> wrote:OK, I will keep them, but the library won't follow that behavior (it will fail if another attribute is added). This probably doesn't matter; this is for the dictionary only, and very few people will create their dictionary by hand once we have a GUI to create them.

**Comment by depryf** [comment]
Good question. I am not entirely sure for, I will have to check the code.

**Comment by depryf** [comment]
I have moved the two XSD files from "docs" to "src/main/resources"; they will be included with the JAR file in the next release. I still have to add some unit tests to make sure the behavior of the library agrees with those files...

**Comment by depryf** [comment]
I added the tests. The weird thing is that to be valid against the XSD, an XML file must define the namespace. 

If a file defines a namespace but doesn't use any prefixes, it will also be valid in the library (because we allow "any" attributes on the root).

If a file defines a namespace and uses prefixes, it won't be accepted by the library.

We can revisit this behavior later if we decide to properly support namespaces.
