### ISSUE TITLE
naaccrNum attribute does not get written when option is selected

### ISSUE THREAD

**Issue by isaackcr** [depryf/naaccr-xml#24]
Using v.0.6, if I select the option "When writing Items in the XML File, also include the NAACCR Number" the output XML file does not contain any naaccrNum attributes. This was tested on the latest synthetic dataset: http://rich.usc.edu/V5_20150529.zip

**Comment by depryf** [comment]
I am missing a lot of unit tests that I hope to add before the conference; they would catch an obvious bug like this one. I will take a look, should be simple to fix.

**Comment by depryf** [comment]
Fixed.
