### ISSUE TITLE
Browse... button is missing from User Dictionary field on "Flat to XML" tab

### ISSUE THREAD

**Issue by isaackcr** [depryf/naaccr-xml#25]
There should be a "Browse..." button for selecting a User Dictionary file when converting a flat to XML file

![screen shot 2015-05-30 at 3 35 49 pm](https://cloud.githubusercontent.com/assets/10038081/7899025/d8972b68-06e1-11e5-8e98-6bd349851421.png)

**Comment by depryf** [comment]
I am pretty sure it's a Window sizing issue; you should be able to see them if you resize your Window. This should already be fixed in version 0.7 (not released yet).

**Comment by depryf** [comment]
Isaac, could you re-test this using the latest version that got released this morning (v0.7); hopefully that should work properly now...

**Comment by isaackcr** [comment]
I tested and it works, thanks !

-Isaac

> On Jun 8, 2015, at 1:20 PM, Fabian Depry <notifications@github.com> wrote:
> 
> Isaac, could you re-test this using the latest version that got released this morning (v0.7); hopefully that should work properly now...
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/depryf/naaccr-xml/issues/25#issuecomment-110097263>.
> 




--Statement of Confidentiality--
This message (and any attachment) is intended only for the recipient
and may contain confidential and/or privileged material. If you have
received this in error, please contact the sender and delete this
message immediately.  Thank you.
