### ISSUE TITLE
Re-add the items data types

### ISSUE THREAD

**Issue by depryf** [depryf/naaccr-xml#28]
Roger gave me spreadsheets with the data types, I just need to extract the types and plug them into the final XLM files. Should be fairly simple.

**Comment by r-friedman** [comment]
I took your XML, parsed it into a table, and added the dataType-related stuff.  You should be able to use your cxv to xml utility directly.
-----Original Message----- From: Fabian Depry Sent: Jun 4, 2015 4:13 AM To: depryf/naaccr-xml Subject: [naaccr-xml] Re-add the items data types (#28) 
Roger gave me spreadsheets with the data types, I just need to extract the types and plug them into the final XLM files. Should be fairly simple.

**Comment by depryf** [comment]
The types have been re-added to the project.

I did find some invalid ones ("integer"); for now those have been changed to "text".

**Comment by depryf** [comment]
Roger asked me to change all "integer" into "digits". I will do that soon.

I did mention I didn't think it was appropriate for the physician fields (it seems to me the NAACCR definition doesn't say they have to be 10 digits), but Roger didn't agree, so we will go with that for now.

**Comment by depryf** [comment]
Never mind about the physician fields, Roger asked me to use "text" for those.

**Comment by depryf** [comment]
Fixed and done.
