### ISSUE TITLE
Add built jar file to github

### ISSUE THREAD

**Issue by isaackcr** [depryf/naaccr-xml#8]

**Comment by depryf** [comment]
Github allows "releases" where a particular branch is tagged with a release number and a distributable (in this case a Jar file) is attached to that tagged. The file is then available on a public Github URL the same way the project it. This is a much better way to release the library than the current way and I will look into switching to that for the next release.

**Comment by depryf** [comment]
This is resolved; the last release (0.5) was done on GitHub. The releases can be accessed from the home page (there is a link on the top of the page).
